version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: equihire-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-equihire_db}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - equihire-network

  redis:
    image: redis:7-alpine
    container_name: equihire-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - equihire-network

  python-ai-engine:
    build: ./python-ai-engine
    container_name: equihire-python-engine
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      - redis
    networks:
      - equihire-network
    volumes:
        - ./python-ai-engine:/app

  ballerina-gateway:
    build: ./ballerina-gateway
    container_name: equihire-ballerina-gateway
    ports:
      - "9090:9090"
    environment:
      - PYTHON_SERVICE_URL=${PYTHON_SERVICE_URL:-http://python-ai-engine:8000}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER:-admin}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_NAME=${POSTGRES_DB:-equihire_db}
    depends_on:
      - postgres
      - redis
      - python-ai-engine
    networks:
      - equihire-network

networks:
  equihire-network:
    driver: bridge
